const schedulesFaker = [
  {
    id: 1,
    flightNo: 'GK 080',
    destination: 'KIX',
    equipment: 'D',
    terminal: '1',
    departure: '00:10',
    groundTime: 60,
    flightDate: null,
  },
  {
    id: 2,
    flightNo: 'KE 650',
    destination: 'ICN',
    equipment: 'D',
    terminal: '1',
    departure: '00:35',
    groundTime: 90,
    flightDate: null,
  },
  {
    id: 3,
    flightNo: 'PR 406',
    destination: 'CTS',
    equipment: 'D',
    terminal: '1',
    departure: '01:55',
    groundTime: 60,
    flightDate: null,
  },
  {
    id: 4,
    flightNo: 'PR 382',
    destination: 'CAN',
    equipment: 'D',
    terminal: '1',
    departure: '02:35',
    groundTime: 60,
    flightDate: null,
  },
  {
    id: 5,
    flightNo: '5J 279',
    destination: 'DPS',
    equipment: 'D',
    terminal: '3',
    departure: '03:50',
    groundTime: 60,
    flightDate: null,
  },
];

export { schedulesFaker };
